
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#    continue-on-error:
#      ${{ contains(fromJson('["snapshot"]'), matrix.emacs_version) }}

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '27.2'

    steps:
      - uses: actions/checkout@v2
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run a one-line script
        run: sh publish.sh

      - name: Check stuff
        run: ls $GITHUB_WORKSPACE
