
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
#    continue-on-error:
#      ${{ contains(fromJson('["snapshot"]'), matrix.emacs_version) }}

    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '27.2'

    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Run publish script
        run: sh build/publish.sh

      - name: Deploy to github pages
        uses: JamesIves/github-pages-deploy-action@4.2.5
        with:
          branch: html
          folder: .
